#!/bin/bash
. ./lib

options=()

items=$(pacman -Ssq openbox)
for item in $items; do
  case $item in
    "lxappearance-obconf") options+=("$item" "" off);;
    *) options+=("$item" "" on);;
  esac
done

sel=$(whiptail --backtitle "$apptitle" --title "Openbox Install :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

exit 0
