#!/bin/bash
. ./lib

options=()
options+=("wireplumper" "(modern)")
options+=("pulseaudio" "(legacy)")
options+=("pipewire-media-session" "")

defaultitem=""
sel=$(dialog --backtitle "$apptitle" --title "System Sound Menu :" --default-item "$defaultitem" --cancel-button "Back" --menu "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

script install/system/sound/$sel

exit 0
