#!/bin/bash
. ./lib

options=()
options+=("pipewire-media-session" "" on)
options+=("pipewire-alsa" "" on)
options+=("pipewire-jack" "" on)
options+=("pipewire-pulse" "" on)
options+=("pipewire-v4l2" "" on)
options+=("pipewire-zeroconf" "" on)
options+=("gst-plugin-pipewire" "" on)
options+=("easyeffects" "" off)
options+=("pipewire-x11-bell" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "System PPMediaSession Install" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
