#!/bin/bash
. ./lib

options=()
options+=("deepin" "")
options+=("deepin-extra" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Deepin Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'deepin')
    require install/desktop/deepin/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/deepin/packages
    script install/desktop/deepin/packages
  ;;
  'deepin-extra')
    require install/desktop/deepin/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/deepin/packages
    script install/desktop/deepin/packages
  ;;
esac

exit 0
