#!/bin/bash
. ./lib

options=()

package="deepin deepin-extra"
items=$(pacman -Sqg $package)
for item in $items; do
  options+=("$item" "" on)
done

sel=$(whiptail --backtitle "$apptitle" --title "$package Install :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

config_xinitrc() { #{{{
    #create a xinitrc file in home user directory
    cp -fv /etc/X11/xinit/xinitrc /home/${username}/.xinitrc
    echo -e "exec $1" >> /home/${username}/.xinitrc
    chown -R ${username}:users /home/${username}/.xinitrc
} #}}}

config_xinitrc "startdde"

exit 0
