#!/bin/bash
. ./lib

options=()
options+=("bash-completion" "Best completion in bash" on)
options+=("lsof" "ls open file" on)
options+=("dmidecode" "Hardware infos" on)
options+=("nmon" "System monitor" on)
options+=("mc" "Dual pane file explorer" off)
options+=("powertop" "power mon and management" off)
options+=("dialog" "Dialog boxes for script" off)
options+=("gpm" "Console mouse support" off)

sel=$(whiptail --backtitle "$apptitle" --title "Console Basic packages :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"gpm"')
      svcstart gpm
      svcenable gpm
    ;;
  esac
done

exit 0
