#!/bin/bash
. ./lib

options=()
options+=("zip" "ZIP files" on)
options+=("unzip" "ZIP files" on)
options+=("unrar" "RAR files" on)
options+=("p7zip" "File Archiver" on)
options+=("lzop" "LZO Compressor" on)

sel=$(whiptail --backtitle "$apptitle" --title "Console Compression Tools :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
