#!/bin/bash
. ./lib

options=()
options+=("pacman-contrib" "Pacman contrib tools" on)
options+=("base-devel" "Build tools" on)
options+=("bash-completion" "Best completion in bash" on)
options+=("lsof" "ls open file" on)
options+=("dmidecode" "Hardware infos" on)
options+=("dialog" "Dialog boxes for script" on)
options+=("nmon" "System monitor" off)
options+=("mc" "Dual pane file explorer" off)
options+=("vim" "Vi Improved" off)
options+=("neofetch" "system information tool" off)
options+=("powertop" "power mon and management" off)
options+=("gpm" "Console mouse support" off)
options+=("liveroot" "(AUR) root overlay fs" off)

sel=$(whiptail --backtitle "$apptitle" --title "Console Generic packages :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"liveroot"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"gpm"')
      svcstart gpm
      svcenable gpm
    ;;
  esac
done

exit 0
