#!/bin/bash
. ./lib

options=()
options+=("Generic" "")
options+=("Compression Tools" "")
options+=("Network Tools" "")
options+=("Webbrowser" "")
options+=("Recovery Tools" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  "Generic") script install/console/generic;;
  "Compression Tools") script install/console/compression-tools;;
  "Network Tools") script install/console/network-tools;;
  "Webbrowser") script install/console/webbrowser;;
  "Recovery Tools") script install/console/recovery-tools;;
esac

exit 0
