#!/bin/bash
. ./lib

options=()
options+=("ddrescue" "HD recovery tool" off)
options+=("dd_rescue" "HD recovery tool" off)
options+=("partclone" "Copy used block on partition" off)

sel=$(dialog --backtitle "$apptitle" --title "Console Recovery Tools :" --cancel-button "Back" --checklist "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
