#!/bin/bash
. ./lib

options=()
options+=("elinks" "" off)
options+=("links" "" off)
options+=("lynx" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "Console Web Browser :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
