#!/bin/bash

prjname=archdi
version=$(date +"%Y.%m.%d.%H.%M.%S")
branch=$(git rev-parse --abbrev-ref HEAD)

ssh -T git@github.com
if [ ! "$?" = "1" ]; then
  echo "No Github ssh key loaded exiting..."
  exit 1
fi

scp matmoul@web.sourceforge.net:/home/frs/project/$prjname/README.txt /dev/null
if [ ! "$?" = "1" ]; then
  echo "No Sourceforge ssh key loaded exiting..."
  exit 1
fi


clear
read -p "Current branch is $branch. Continue ? (y/N)" choice
case "$choice" in 
  n|N|'' )
    echo "cancel build !"
    exit 1
  ;;
  y|Y ) echo "Begin Build Release...";;
  * )
    echo "cancel build !"
    exit 1
  ;;
esac
echo "Building version $version..."
echo ""

echo "Finalise lib script..."
sed -i /apptitle=/c\apptitle=\""Arch Linux Desktop Install (archdi) - Version: $version (GPLv3)"\" lib
sed -i /baseurl=/c\baseurl=https://raw.githubusercontent.com/MatMoul/archdi/master lib

echo "Make last commit..."
git commit -a -m "New Release : $version"

if [ ! "$branch" = "master" ]; then
  echo "Merge branch $branch to master..."
  git checkout master
  git merge $branch

  read -p "Delete branch $branch ? (Y/n)" choice
  case "$choice" in 
    y|Y|'' )
      git branch -D $branch
    ;;
  esac
fi

read -p "Publish to server ? (Y/n)" choice
case "$choice" in 
  n|N )
    exit 1
  ;;
esac

echo "Push release..."
git push


#Sourceforge :

targetpath=.build/$version
mkdir -p $targetpath
cp -R * $targetpath

echo "Finalise lib script..."
sed -i "/baseurl=/c\baseurl=http://downloads.sourceforge.net/project/archdi/release/pkg/$version" $targetpath/lib

echo "Publish release..."
scp -r $targetpath matmoul@web.sourceforge.net:/home/frs/project/$prjname/release/pkg/

#echo "Update redirect page..."
#pubfile=.build/index.php
#echo "<?php" > $pubfile
#echo "header(\"Location: http://downloads.sourceforge.net/project/$prjname/release/$version/$prjname\");" >> $pubfile
#echo "exit;" >> $pubfile
#echo "?>" >> $pubfile
#scp -r $pubfile matmoul@web.sourceforge.net:/home/project-web/$prjname/htdocs/$prjname/

rm -R .build
