#!/bin/bash
. ./lib

options=()
options+=("dmenu" "" on)
options+=("slstatus" "" on)

sel=$(whiptail --backtitle "$apptitle" --title "Plasma Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"dmenu"') pkg="$pkg dmenu";;
    '"slstatus"') aurpkg="$aurpkg slstatus-git";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
