#!/bin/bash
. ./lib

options=()
options+=("dwm" "" on)

sel=$(whiptail --backtitle "$apptitle" --title "DWM:" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"dwm"') aurpkg="$aurpkg dwm";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
