#!/bin/bash
. ./lib

options=()
options+=("DWM" "")
options+=("Complements" "")

defaultitem="DWM"
sel=$(whiptail --backtitle "$apptitle" --title "DWM Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'DWM') script install/desktop/dwm/dwm;;
  'Complements') script install/desktop/dwm/complements;;
esac

exit 0
