#!/bin/bash
. ./lib

options=()
options+=("thunderbird" "(GTK)" off)
options+=("evolution" "(GTK)" off)
options+=("evolution-bogofilter" "" off)
options+=("evolution-spamassassin" "" off)
options+=("evolution-ews" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "E-Mails applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"thunderbird"') choosepkg "thunderbird-i18n-";;
  esac
done

exit 0
