#!/bin/bash
. ./lib

options=()
options+=("Web Browser" "")
options+=("Torrent" "")
options+=("E-Mail" "")


defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Internet Apps :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  "Web Browser") script install/apps/internet/webbrowser;;
  "Torrent") script install/apps/internet/torrent;;
  "E-Mail") script install/apps/internet/mail;;
esac

exit 0
