#!/bin/bash
. ./lib

options=()
options+=("transmission-gtk" "(GTK)" off)
options+=("transmission-qt" "(QT)" off)
options+=("ktorrent" "(QT)" off)
options+=("qbittorrent" "(QT)" off)
options+=("deluge" "(PYTHON)" off)
options+=("tixati" "(AUR) (GTK)" off)

sel=$(whiptail --backtitle "$apptitle" --title "Torrent applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"tixati"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
