#!/bin/bash
. ./lib

options=()
options+=("chromium" "" off)
options+=("chromium-pepper-flash" "(AUR) Remoennded" off)
options+=("chromium-pepper-flash-standalone" "(AUR)" off)
options+=("firefox" "" off)
options+=("flashplugin" "" off)
options+=("freshplayerplugin-git" "(AUR) Recommended" off)
options+=("freshplayerplugin" "(AUR)" off)
options+=("opera" "" off)
options+=("midori" "" off)
options+=("midori-gtk2" "" off)

sel=$(whiptail --backtitle "$apptitle" --title "Web Browser applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"chromium-pepper-flash"' | \
    '"chromium-pepper-flash-standalone"' | \
    '"freshplayerplugin-git"' | \
    '"freshplayerplugin"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"firefox"') choosepkg "firefox-i18n-";;
  esac
done

exit 0
