#!/bin/bash
. ./lib

options=()
options+=("chromium" "(GTK)" off)
options+=("pepper-flash" "" off)
options+=("firefox" "(GTK)" off)
options+=("firefox-i18n" "" off)
options+=("opera" "(GTK)" off)
options+=("opera-ffmpeg-codecs" "Non-free codecs" off)
options+=("seamonkey" "(GTK)" off)
options+=("seamonkey-i18n" "(AUR)" off)
options+=("midori" "(GTK)" off)
options+=("falkon" "(QT)" off)
options+=("vivaldi" "(AUR) (GTK)" off)
options+=("vivaldi-ffmpeg-codecs" "(AUR) Non-free codecs" off)

sel=$(whiptail --backtitle "$apptitle" --title "Web Browser applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"vivaldi"' | \
    '"vivaldi-ffmpeg-codecs"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    '"firefox-i18n"' | \
    '"seamonkey-i18n"') pkg="$pkg";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"firefox-i18n"') choosepkg "firefox-i18n-";;
    '"seamonkey-i18n"') chooseaurpkg "seamonkey-i18n-";;
  esac
done

exit 0
