#!/bin/bash
. ./lib

options=()
options+=("config" "/boot/refind_linux.conf")
options+=("global config" "/boot/refind_linux.conf")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "rEFInd Config Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'config') editfile /boot/refind_linux.conf;;
  'global config') editfile /boot/EFI/refind/refind.conf;;
esac

exit 0
