#!/bin/bash
. ./lib

options=()
options+=("gsfonts" "" on)
options+=("sdl_ttf" "" on)
options+=("ttf-bitstream-vera" "" on)
options+=("ttf-dejavu" "" on)
options+=("ttf-liberation" "" on)
options+=("xorg-fonts-type1" "" on)

sel=$(dialog --backtitle "$apptitle" --title "XOrg Default Fonts :" --cancel-button "Back" --checklist "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
