#!/bin/bash
. ./lib

options=()
options+=("ttf-ms-fonts" "(AUR)" off)

items=$(pacman -Ssq ttf-)
for item in $items; do
  options+=("$item" "" off)
done

sel=$(dialog --backtitle "$apptitle" --title "XOrg TTF :" --cancel-button "Back" --checklist "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    "ttf-ms-fonts") aurpkg="$aurpkg ttf-ms-fonts";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
