#!/bin/bash
. ./lib

options=()
options+=("0AD" "" off)
options+=("puzzles" "" off)

sel=$(dialog --backtitle "$apptitle" --title "Game applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
