#!/bin/bash
. ./lib

options=()
options+=("Gnome" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Gnome Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Gnome') script install/desktop/gnome/gnome;
  'Gnome Extra') script install/desktop/gnome/extra;
esac

exit 0