#!/bin/bash
. ./lib

options=()
options+=("Gnome Base" "")
options+=("Gnome Extra" "")
options+=("Gnome Tweaks" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Gnome Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Gnome Base') script install/desktop/gnome/base;;
  'Gnome Extra') script install/desktop/gnome/ex;;
  'Gnome Tweaks') script install/desktop/gnome/twk;;
esac

exit 0