#!/bin/bash
. ./lib

options=()
options+=("Plasma5" "")
options+=("XFCE4" "")
options+=("Gnome" "")
options+=("Cinnamon" "")
options+=("LXDE" "")
options+=("LXQt" "")
options+=("Mate" "")
options+=("Enlightenment" "")
options+=("Openbox" "")
options+=("Deepin" "")
#options+=("KDE4" "(AUR) End of life")
#options+=("GnuStep" "")
#options+=("i3" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Install Desktop Menu :" --menu "First item is most maintained" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

helpwanted(){
  msg="As you can imagine, it's difficult to manage desktop setup that I not use every day.\n\nIf you are motivated and trained, join me on https://github.com/MatMoul/archdi-pkg to support this desktop enivironnement."
  whiptail --backtitle "$apptitle" --title "Help Wanted" --msgbox "$msg" 0 0
}

case $sel in
  'Plasma5') menu install/desktop/plasma5/menu;;
  'XFCE4')
    helpwanted
    menu install/desktop/xfce4/menu
  ;;
  'Gnome')
    helpwanted
    menu install/desktop/gnome/menu
  ;;
  'Cinnamon')
    helpwanted
    script install/desktop/cinnamon/packages
  ;;
  'LXDE')
    helpwanted
    script install/desktop/lxde/packages
  ;;
  'LXQt')
    helpwanted
    menu install/desktop/lxqt/menu
  ;;
  'Mate')
    helpwanted
    menu install/desktop/mate/menu
  ;;
  'Enlightenment')
    helpwanted
    script install/desktop/enlightenment/packages
  ;;
  'Openbox')
    helpwanted
    script install/desktop/openbox/packages
  ;;
  'Deepin')
    helpwanted
    menu install/desktop/deepin/menu
  ;;
  #'KDE4') menu install/desktop/kde4/menu;;
esac

exit 0
