#!/bin/bash
. ./lib

options=()
options+=("config" "/boot/syslinux/syslinux.cfg")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Syslinux Config Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'config') editfile /boot/syslinux/syslinux.cfg;;
esac

exit 0
