#!/bin/bash
. ./lib

options=()
options+=("initcpio" "")
if [ -f /boot/grub/grub.cfg ]; then
  options+=("grub" "")
fi

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Boot Configuration :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'initcpio') menu config/boot/initcpio/menu;;
  'grub') menu config/boot/grub/menu;;
esac

exit 0
