#!/bin/bash
. ./lib

options=()
options+=("Bash" "")
options+=("Firewall" "")
options+=("Accounts" "")
options+=("Systemd" "")
if [ -f /usr/bin/Xorg ]; then
  options+=("XOrg" "")
fi
options+=("Boot" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Config Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Bash') menu config/bash/menu;;
  'Firewall') menu config/firewall/menu;;
  'Accounts') menu config/accounts/menu;;
  'Systemd') menu config/systemd/menu;;
  'XOrg') menu config/xorg/menu;;
  'Boot') menu config/boot/menu;;
esac

exit 0
