#!/bin/bash
. ./lib

options=()
options+=("Services" "")
options+=("" "")
options+=("timedatectl" "")

defaultitem="Services"
sel=$(whiptail --backtitle "$apptitle" --title "Systemd Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Services') menu config/systemd/services/menu;;
  'timedatectl') menu config/systemd/timedatectl/menu;;
esac

exit 0
