#!/bin/bash
. ./lib

options=()
options+=("virtualbox-guest-utils" "(For Virtualbox)" off)
options+=("nvidia" "" off)
options+=("nvidia-390xx" "(AUR) End of life" off)
#options+=("nvidia-340xx" "" off) #DEAD ?
options+=("nvidia-dkms" "(For custom kernel)" off)
options+=("nvidia-390xx-dkms" "(AUR) (For custom kernel)" off)
#options+=("nvidia-340xx-dkms" "(For custom kernel)" off) #DEAD ?
#options+=("catalyst" "(AUR)" off)
#options+=("catalyst-total-hd234k" "(AUR)" off)

sel=$(whiptail --backtitle "$apptitle" --title "XOrg video drivers :" --checklist "Choose video drivers for your system :" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"nvidia-390xx"' | \
    '"nvidia-390xx-dkms"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
