#!/bin/bash
. ./lib

options=()
options+=("Users" "")
options+=("Sudoers" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Accounts Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Users') menu config/accounts/users/menu;;
  'Sudoers') menu config/accounts/sudoers/menu;;
esac

exit 0
