#!/bin/bash
. ./lib

options=()
options+=("config" "/etc/default/grub")
options+=("grub-mkconfig" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Grub Config Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'config') editfile /etc/default/grub;;
  'grub-mkconfig')
    clear
    echo "grub-mkconfig -o /boot/grub/grub.cfg"
    grub-mkconfig -o /boot/grub/grub.cfg
    pressanykey
  ;;
esac

exit 0
