#!/bin/bash
. ./lib

options=()
options+=("Kernel" "")
options+=("Services" "")
options+=("File System" "")
options+=("Sound" "")
options+=("Print" "")

defaultitem=""
sel=$(dialog --backtitle "$apptitle" --title "System Install Menu :" --default-item "$defaultitem" --cancel-button "Back" --menu "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Kernel') menu install/system/kernel/menu;;
  'Services') script install/system/services/menu;;
  'File System') script install/system/filesystem;;
  'Sound') menu install/system/sound/menu;;
  'Print') script install/system/print;;
esac

exit 0
