#!/bin/bash
. ./lib

options=()
options+=("kwallet-pam" "" on)
options+=("partitionmanager" "" on)
options+=("gnome-keyring" "" on)
options+=("qt5-multimedia" "" on)
options+=("kdeconnect" "" off)
options+=("sshfs" "(For kdeconnect)" off)

sel=$(whiptail --backtitle "$apptitle" --title "Plasma Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"kwallet-pam"')
      sed -i '/auth/a auth  optional  pam_kwallet5.so' /etc/pam.d/sddm
      sed -i '/session/a session  optional  pam_kwallet5.so' /etc/pam.d/sddm
    ;;
  esac
done

exit 0
