#!/bin/bash
. ./lib

options=()
options+=("Plasma Packages" "")
options+=("Localisations" "kde-l10n-")
options+=("KDE Apps Meta Full" "kde-applications-meta")
options+=("KDE Apps Full" "kde-applications")
options+=("KDE Apps" "")
options+=("Complements" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Plasma5 Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'Plasma Packages') script install/desktop/plasma5/plasma-packages;;
  'Localisations') script install/desktop/plasma5/localisations;;
  'KDE Apps Meta Full')
    if ( confirm "This option install all KDE applications with meta packages.\n\nInstall KDE Meta Full (pacman -S kde-applications-meta) ?" ) then
      instpkg "kde-applications-meta" ""
    fi
  ;;
  'KDE Apps Full')
    if ( confirm "This option install all KDE applications.\n\nInstall KDE Full (pacman -S kde-applications) ?" ) then
      instpkg "kde-applications" ""
    fi
  ;;
  'KDE Apps') script install/desktop/plasma5/kdeapps;;
  'Complements') script install/desktop/plasma5/complements;;
esac

exit 0
