#!/bin/bash
. ./lib

options=()
options+=("amarok" "Audio Player" off)
options+=("guayadeque" "Audio Player" off)
options+=("clementine" "Audio Player" off)
options+=("mixxx" "Audio Player" off)
options+=("gmusicbrowser" "(AUR) Audio Player" off)

sel=$(whiptail --backtitle "$apptitle" --title "Audio Player applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"gmusicbrowser"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
