#!/bin/bash
. ./lib

options=()
options+=("clementine" "(QT) Audio Player" off)
options+=("mixxx" "(QT) Audio Player" off)
options+=("quodlibet" "(GTK) Audio Player" off)
options+=("elisa" "(QT) Audio Player" off)
options+=("amarok" "(AUR) (QT) Audio Player" off)
options+=("guayadeque" "(AUR) (GTK) Audio Player" off)
options+=("gmusicbrowser" "(AUR) (GTK) Audio Player" off)

sel=$(dialog --backtitle "$apptitle" --title "Audio Player applications :" --cancel-button "Back" --checklist "Choose what you want" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    "amarok" | \
    "guayadeque" | \
    "gmusicbrowser") aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
