#!/bin/bash
. ./lib

options=()
options+=("GStreamer" "")
options+=("Audio Player" "")
options+=("Video Player" "")
options+=("Video Tools" "")
options+=("Burner Tools" "")


defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Multimedia Apps :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  "GStreamer") script install/apps/multimedia/gstreamer;;
  "Audio Player") script install/apps/multimedia/audioplayer;;
  "Video Player") script install/apps/multimedia/videoplayer;;
  "Video Tools") script install/apps/multimedia/videotools;;
  "Burner Tools") script install/apps/multimedia/burnertools;;
esac

exit 0
