#!/bin/bash
. ./lib

options=()
options+=("vlc" "(QT) Video player" off)
options+=("smplayer" "(QT) Video player" off)
options+=("smtube" "(QT) Youtube Player" off)
options+=("mpv" "(GTK) Recommended for smplayer" off)
options+=("celluloid" "(GTK) Video player" off)
#options+=("streamstudio-bin" "(AUR) Stream video Player" off)

sel=$(whiptail --backtitle "$apptitle" --title "Video Player applications :" --checklist "Choose what you want" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"streamstudio-bin"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

exit 0
