#!/bin/bash
. ./lib

options=()
options+=("oxygen-icons" "Default Icon Theme" on)
options+=("connman" "Network Manager" on)
options+=("lximage-qt" "(AUR)" on)
options+=("lximage-qt-git" "(AUR)" off)
options+=("obconf-qt" "(AUR)" on)
options+=("obconf-qt-git" "(AUR)" off)
options+=("qterminal" "(AUR)" on)
options+=("qterminal-git" "(AUR)" off)
options+=("lxqt-connman-applet-git" "(AUR) Applet for NM" off)
options+=("sddm" "display manager" on)


sel=$(whiptail --backtitle "$apptitle" --title "LXQt Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"lxqt-connman-applet-git"' | \
    '"lximage-qt-git"' | \
    '"lximage-qt"' | \
    '"obconf-qt-git"' | \
    '"obconf-qt"' | \
    '"qterminal-git"' | \
    '"qterminal"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"sddm"') svcenable sddm;;
  esac
done

exit 0
