#!/bin/bash
. ./lib

options=()
options+=("sddm" "Display manager" on)
options+=("oxygen-icons" "Default Icon Theme" on)
options+=("connman" "Network Manager" on)
options+=("obconf" "" on)
options+=("lxqt-connman-applet-git" "(AUR) Applet for NM" off)


sel=$(whiptail --backtitle "$apptitle" --title "LXQt Complements :" --checklist "" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  case $itm in
    '"lxqt-connman-applet-git"') aurpkg="$aurpkg $(echo $itm | sed 's/"//g')";;
    *) pkg="$pkg $(echo $itm | sed 's/"//g')";;
  esac
done

instpkg "$pkg" "$aurpkg"

for itm in $sel; do
  case $itm in
    '"sddm"') svcenable sddm;;
  esac
done

exit 0
