#!/bin/bash
. ./lib

options=()
options+=("LXQt" "")
options+=("Complements" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "LXQt Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'LXQt') script install/desktop/lxqt/packages;;
  'Complements') script install/desktop/lxqt/complements;;
esac

exit 0
