#!/bin/bash
. ./lib

options=()

items=$(pacman -Ssq lxqt)
for item in $items; do
  options+=("$item" "" on)
done

sel=$(dialog --backtitle "$apptitle" --title "LXQT Install :" --cancel-button "Back" --checklist "" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)

if [ ! "$?" = "0" ]; then
  exit 1
fi

for itm in $sel; do
  pkg="$pkg $(echo $itm | sed 's/"//g')"
done

instpkg "$pkg" "$aurpkg"

exit 0
