#!/bin/bash
. ./lib

options=()
options+=("cinnamon" "")
options+=("gnome-terminal" "")

defaultitem=""
sel=$(whiptail --backtitle "$apptitle" --title "Cinnamon Install Menu :" --menu "" --default-item "$defaultitem" --cancel-button "Back" 0 0 0 \
  "${options[@]}" \
  3>&1 1>&2 2>&3)
if [ ! "$?" = "0" ]; then
  exit 1
fi
sed -i "/^defaultitem=/c\defaultitem=\"$sel\"" $0

case $sel in
  'cinnamon')
    require install/desktop/cinnamon/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/cinnamon/packages
    script install/desktop/cinnamon/packages
  ;;
  'cinnamon-translations')
    require install/desktop/cinnamon/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/cinnamon/packages
    script install/desktop/cinnamon/packages
  ;;
  'gnome-terminal')
    require install/desktop/cinnamon/packages 755
    sed -i "/^package=/c\package=\"$sel\"" install/desktop/cinnamon/packages
    script install/desktop/cinnamon/packages
  ;;
esac

exit 0
